services:
  #frontend:
    #build:
    #  context: ./front
    #  dockerfile: Dockerfile
    #image: php:7.4-apache
    #ports:
    #  - 8083:80

  # DEV
  frontend:
    build: .
    volumes:
      - ./front:/var/www/html
    ports:
      - 8083:80

  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    image: spatulox/pa-api:latest
    ports:
      - 8081:80
    volumes:
      - ./api:/var/www/html/
    depends_on:
      - database

  ticket:
    image: spatulox/pa-ticket:latest
    ports:
      - 8085:8085
    environment:
      - DB_CONTAINER_NAME=database
    depends_on:
      - database


  database:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=apiDev_db
      - MYSQL_USER=apiDev
      - MYSQL_PASSWORD=password

volumes:
  db-data:
